### ISSUE TITLE
UUP Dump can't see the 1903 update offered to 17763.529 in Retail

### ISSUE THREAD

**Issue by Googulator** [uup-dump/website#2]
Microsoft has started rolling out the 1903 update to those currently on build 17763.529 who have the new "Additional updates available" experience enabled (which is being rolled out via WIL/Velocity as a staged feature release, currently at a low but nonzero percentage).

The actual update itself is apparently staged at 0% rollout level, i.e. seekers only.

UUP Dump can't see this build in Retail, even if I set the build number of the mock client to 17763.529, despite the fact that the Seeker flag is being set already. The servers are most likely checking for a new flag, supported only by 17763.529 and beyond, indicating that the new "Additional updates" experience is enabled, which UUP Dump isn't setting currently.

**Comment by whatever127** [comment]
I have fixed a issue that prevented updates which are marked as _OptionalInstall_ from being considered as UUP update. I have also updated attributes by guessing values.

The result is that it is possible to retrieve 1903 update in Retail ring, but the chance is only about 10%.
![result](https://user-images.githubusercontent.com/46111995/58343064-68ab8500-7e52-11e9-8b45-618b937e1ffc.png)

Since the WU responses are cached for 90 seconds, it is almost impossible to get 1903 in Retail ring.
