### ISSUE TITLE
Cloudflare AJAX and select editions.

### ISSUE THREAD

**Issue by leftl** [uup-dump/website#20]
I understand this is a bit of a niche issue and not the fault of the website directly, but using uBlock Origin on medium-mode (block 3rd-party scripts + frames) displays the selection of editions even though "create additional editions" download method is not selected. Additionally, it blocks the `Learn more` link which contains the information needed to build Education/Enterprise editions.
<img width="816" alt="Capture" src="https://user-images.githubusercontent.com/19383474/69014685-b73d6600-0941-11ea-9809-510376cbdcfd.PNG">
I tried building two different ISOs before I realized this was happening, but was able to easily fix both by just manually running the create-virtual-editions script. Is it possible to add logic to prevent this, or make it a bit more obvious that "create virtual editions" is required for certain editions on the confirmation page?

Thanks for this awesome project!

**Comment by whatever127** [comment]
Blocking cloudflare effectively disabled all JavaScript on the website for you. This is not related to the website itself, but the CloudFlare's RocketLoader which is enabled on the uupdump.ml domain.

I have now disabled RocketLoader in CloudFlare settings, because it was only causing problems with JavaScript.

If you will notice problems now, please reopen this issue, so I will take other steps to fix this.
