### ISSUE TITLE
uupdump.ml website it's unavailable

### ISSUE THREAD

**Issue by mathpfvr** [uup-dump/website#23]
![Captura de Tela (1)](https://user-images.githubusercontent.com/7264001/70630845-073ede00-1c0b-11ea-9991-76bf20db7493.png)

**Comment by CrafterLaughter** [comment]
It's back up.  Yesterday, I went to use UUP Dump Downloader & noticed it wasn't pulling the builds and I came across uupdump.ml instead.  I see @whatever127 is behind both projects.

This morning when I refreshed the UUP Dump Downloader GitLab page it now says the UUP Downloader project is archived. I'm pretty sure it didn't say that last night, so I imagine he was doing maintenance last night.

@whatever127  Can you put a link on the UUP Downloader GitLab page that lets people know they should use uupdump.ml instead?  I just found via via google and happened to notice your handle on both projects.

**Comment by mathpfvr** [comment]
does not working for me ):
and UUP Dump Downloader too, powershell closing

**Comment by CrafterLaughter** [comment]
I just checked and it works with my FF and Chrome.  I see from your screenshot you received a Spanish HTML response.  I'm guessing it's getting hung up somewhere with your local or internet DNS.  I checked to see if they have a static IP...unfortunately they're on a shared server.

In the meantime https://uup.rg-adguard.net/   is a viable substitute.  (I'm not 100% if it's the same dev behind uupdump.ml but I do believe it's legit because people discuss both as viable in this Github here:  https://github.com/WOA-Project/WoA-Installer-Rpi/issues/25

**Comment by mathpfvr** [comment]
Error: "Unable to retrieve list of available builds" on uupdump downloader 1.2.3 and 1.2.4

![Captura de Tela (2)](https://user-images.githubusercontent.com/7264001/70823891-b8867500-1dbf-11ea-997b-1d3fd7f81649.png)

**Comment by CrafterLaughter** [comment]
I'm pretty sure the UUP Dump Downloader Project was archived a couple days ago.  https://gitlab.com/uup-dump/downloader

The page says " Archived project! Repository and other project resources are read-only" 

When it comes to uupdump.ml did you try another DNS server or another browser?

If still no luck try https://uup.rg-adguard.net

**Comment by whatever127** [comment]
> This morning when I refreshed the UUP Dump Downloader GitLab page it now says the UUP Downloader project is archived. I'm pretty sure it didn't say that last night, so I imagine he was doing maintenance last night.

UUP dump downloader is no longer developed, because it became an unmaintainable mess. The project was archived many months ago. I will modify that repository to state that the application is dead.

---

> I just checked and it works with my FF and Chrome. I see from your screenshot you received a Spanish HTML response. I'm guessing it's getting hung up somewhere with your local or internet DNS. I checked to see if they have a static IP...unfortunately they're on a shared server.

UUP dump is hosted on shared server and uses Cloudflare. I can't host it on anything better due to financial reasons.

---

> In the meantime https://uup.rg-adguard.net/ is a viable substitute. (I'm not 100% if it's the same dev behind uupdump.ml but I do believe it's legit because people discuss both as viable in this Github here: WOA-Project/WoA-Installer-Rpi#25

uup.rg-adguard.net is developed by rg-adguard, and uses heavily modified very old version of UUP dump. I do not recommend to use it, because the author does not contribute anything to UUP dump.

---

I'm closing, because I don't see any problems with the website.

**Comment by mathpfvr** [comment]
Will the website continue to be maintained bro?

**Comment by whatever127** [comment]
Website is still maintained and will continue to be maintained.

**Comment by mathpfvr** [comment]
Strange the site is not opening for me :/
