### ISSUE TITLE
UUP Dump Website Not Working. Unable to retrieve data from Windows Update servers. Reason: EMPTY_FILELIST

### ISSUE THREAD

**Issue by KedarWolf** [uup-dump/website#44]
I'm trying to download 19041.1 for someone with UUP Dump, get the below error. :(

```
Extracting UUP converter...

Retrieving aria2 script...

09/13 16:15:48 [NOTICE] Downloading 1 item(s)

09/13 16:15:49 [NOTICE] Download complete: D:/19041.1_amd64_en-us_multi_be8233f3_convert/files/aria2_script.30040.txt

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8e1bab|OK  |      43B/s|D:/19041.1_amd64_en-us_multi_be8233f3_convert/files/aria2_script.30040.txt

Status Legend:
(OK):download completed.

Unable to retrieve data from Windows Update servers. Reason: EMPTY_FILELIST
If this problem persists, most likely the set you are attempting to download was removed from Windows Update servers.

Press any key to continue . . .

```

**Comment by awuctl** [comment]
That error is correct (though it may not be obvious why at first) and the 'workaround' is very simple.
Windows Update servers do not store information for the **contents of 19041.1** as that specific update is not offered anymore.

Windows Update will never offer that update to anyone so it has been removed from the Unified Update Platform; Only newer versions are available.
Newer revisions (19041.**x**, x - revision number, applies to any build) of a given build are the base build (".1") + all Cumulative Update (CU) files.

If you build an image from the file list for [19041.508](https://uupdump.ml/selectlang.php?id=e7366588-f2c5-4ac2-a608-3a0b9ae796d3) but ignore (that is, do not integrate) the [CU files](https://uupdump.ml/findfiles.php?id=e7366588-f2c5-4ac2-a608-3a0b9ae796d3&q=Windows10%20KB), you will have a **19041.1 image**.

The option to not integrate Cumulative Updates was available on the website using the `Integrate updates when available (Windows converter only)` checkbox but it was disabled due to some misunderstanding (or so I'm told). You can manually toggle this using the `AddUpdates =0` option in the converter config.

The entire process of creating 19041.1 as of now is as follows:
1. Find the latest 19041 build on UUP dump. (As of now available as the **Latest Public Release build**, 19041.508)
2. Download the package you want.
3. Extract the package somewhere safe.
4. Open `ConvertConfig.ini` and change `AddUpdates   =1` to `AddUpdates   =0`.
6. Run uup_download_\*platform\*
7. Done.

**Comment by ShuoLiu-Max** [comment]
这个版本下架了，需要更换其他的版本

**Comment by ShuoLiu-Max** [comment]
This version of windows is off the web

**Comment by andythegreat87** [comment]
One Windows 11, I cannot get the UUP to work, when I press any key it does not work , I also get this 

_"Current directory contains spaces in its path.
Please move or rename the directory to one not containing spaces.

Press any key to continue . . ."_

**Comment by Zuma132** [comment]
the problem i met is the same as awuctl, but this problem is not solved when i changed Addupdates =1 to Addupdates =0

**Comment by zuidwijk** [comment]
Same issue here, and I figure it out what caused is... the uup_downloadxxxx.sh file contains a link (line 55) opening that link gives #UUPDUMP_ERROR:EMPTY_FILELIST

Now figuring out how to solve it

**Comment by bingaling123** [comment]
I've been getting an Operation not permitted error when trying to execute uup_download_macos.sh. It worked previously and I really don't get it. I added Terminal to Full Disk Access and the permissions are fine :/

**Comment by MarcelKohlmeyer** [comment]
> I've been getting an Operation not permitted error when trying to execute uup_download_macos.sh. It worked previously and I really don't get it. I added Terminal to Full Disk Access and the permissions are fine :/

Might be much to late but that error is about filepermissions. The file is missing the flag to be executable.
You can add it easily by running `chmod +x ./uup_download_macos.sh` and you should be able to execute it
